<?php
/*                  AUTOGENERATED SKELETON CLASS
This skeleton class was generated by the Dat0r library (https://github.com/berlinonline/Dat0r)
on 2014-01-10 14:35:37 and allows to alter the behaviour of the 'Author' module.
This file is only generated if doesn't exist so eventual modifications are safe. */

namespace Honeybee\Domain\Author;

use Honeybee\Domain\Author\Base;

/**
 * The AuthorModule class reflects the declared structure of the 'Author' entity.
 * It holds the meta data necessary to manage/initiate 'AuthorDocument' lifecycles.
 */
class AuthorModule extends Base\AuthorModule
{

}
