<?php
/*                  AUTOGENERATED SKELETON CLASS
This skeleton class was generated by the Dat0r library (https://github.com/berlinonline/Dat0r)
on 2014-01-10 14:35:37 and allows to alter the behaviour of 'Author' documents.
This file is only generated if doesn't exist so eventual modifications are safe. */

namespace Honeybee\Domain\Author;

use Honeybee\Domain\Author\Base;

/**
 * Holds the structure definition for Author documents.
 */
class AuthorDocument extends Base\AuthorDocument
{
    public function onBeforeWrite()
    {
        $changed_fields = array();
        foreach ($this->getChanges() as $change) {
            $changed_fields[] = $change->getField()->getName();
        }

        $fullname = $this->getFullname();
        $firstname = $this->getFirstname();
        $lastname = $this->getLastname();

        if (
            empty($fullname)
            || in_array('firstname', $changed_fields)
            || in_array('lastname', $changed_fields)
        ) {
            $this->setFullname($firstname . ' ' . $lastname);
        } elseif (in_array('fullname', $changed_fields)) {
            $this->applyFullname();
        } else {
            if (!empty($fullname) && empty($firstname) && empty($lastname)) {
                $this->applyFullname();
            }
        }

        parent::onBeforeWrite();
    }

    public function setFirstname($firstname)
    {
        parent::setFirstname($firstname);

        $firstname = $this->getFirstname();
        $lastname = $this->getLastname();

        $this->setFullname($firstname . ' ' . $lastname);
    }

    public function setLastname($lastname)
    {
        parent::setLastname($lastname);

        $firstname = $this->getFirstname();
        $lastname = $this->getLastname();

        $this->setFullname($firstname . ' ' . $lastname);
    }

    protected function applyFullname()
    {
        // firstname is automated to be "the first part" of the name string
        $fullname = $this->getFullname();
        $name_parts = explode(' ', $fullname);
        if (isset($name_parts[0])) {
            $this->setFirstname(array_shift($name_parts));
        }
        if (count($name_parts) > 0) {
            $this->setLastname(implode(" ", $name_parts));
        }
    }
}
