<?php
/*                  AUTOGENERATED SKELETON CLASS
This skeleton class was generated by the Dat0r library (https://github.com/berlinonline/Dat0r)
on 2014-01-10 14:35:37 and allows to alter the behaviour of 'Author' documents.
This file is only generated if doesn't exist so eventual modifications are safe. */

namespace Honeybee\Domain\Author;

use Honeybee\Domain\Author\Base;

/**
 * Holds the structure definition for Author documents.
 */
class AuthorDocument extends Base\AuthorDocument
{
    public function onBeforeWrite()
    {
        $fullname = $this->getFullname();
        $this->setFullname($this->getFirstname() . ' ' . $this->getLastname());

        parent::onBeforeWrite();
    }
}
