<?php
/*                  AUTOGENERATED SKELETON CLASS
This skeleton class was generated by the Dat0r library (https://github.com/berlinonline/Dat0r)
on 2013-09-17 01:08:08 and allows to alter the behaviour of the 'WorkflowTicket' module.
This file is only generated if doesn't exist so eventual modifications are safe. */

namespace Honeybee\Domain\Author;

use Honeybee\Domain\Author\Base;

/**
 * The WorkflowTicketModule class reflects the declared structure of the 'WorkflowTicket' entity.
 * It holds the meta data necessary to manage/initiate 'WorkflowTicketDocument' lifecycles.
 */
class WorkflowTicketModule extends Base\WorkflowTicketModule
{

}
