<?php
/*                  AUTOGENERATED SKELETON CLASS
This skeleton class was generated by the Dat0r library (https://github.com/berlinonline/Dat0r)
on 2013-09-17 04:17:31 and allows to alter the behaviour of 'Book' documents.
This file is only generated if doesn't exist so eventual modifications are safe. */

namespace Honeybee\Domain\Book;

use Honeybee\Domain\Book\Base;

/**
 * Holds the structure definition for Book documents.
 */
class BookDocument extends Base\BookDocument
{

}
