<?php
/*                  AUTOGENERATED SKELETON CLASS
This skeleton class was generated by the Dat0r library (https://github.com/berlinonline/Dat0r)
on 2013-09-17 00:49:49 and allows to alter the behaviour of 'Publisher' documents.
This file is only generated if doesn't exist so eventual modifications are safe. */

namespace Honeybee\Domain\Publisher;

use Honeybee\Domain\Publisher\Base;

/**
 * Holds the structure definition for Publisher documents.
 */
class PublisherDocument extends Base\PublisherDocument
{

}
