<?php
/*              AUTOGENERATED CODE - DO NOT EDIT !
This base class was generated by the Dat0r library (https://github.com/berlinonline/Dat0r) 
on 2013-04-17 01:38:55 and is closed to modifications by any meaning.
If you are looking for a place to alter the behaviour of the 'Book' module,
then the 'BookModule' (skeleton) class probally might be a good place to look. */

namespace Honeybee\Domain\Book\Base;

/**
 * Serves as the base class to the 'Book'' module skeleton.
 */
abstract class BookModule extends \Honeybee\Core\Dat0r\Module
{
    /**
     * Creates a new BookModule instance.
     */
    protected function __construct()
    {
        parent::__construct('Book', array( 
            \Dat0r\Core\Runtime\Field\TextField::create('title'), 
            \Dat0r\Core\Runtime\Field\BooleanField::create('ssFlag'), 
            \Dat0r\Core\Runtime\Field\TextField::create('authorFirstname'), 
            \Dat0r\Core\Runtime\Field\TextField::create('authorLastname'), 
            \Dat0r\Core\Runtime\Field\TextField::create('publisherOne'), 
            \Dat0r\Core\Runtime\Field\TextField::create('yearOne'), 
            \Dat0r\Core\Runtime\Field\TextField::create('placeOne'), 
            \Dat0r\Core\Runtime\Field\TextField::create('publisherTwo'), 
            \Dat0r\Core\Runtime\Field\TextField::create('yearTwo'), 
            \Dat0r\Core\Runtime\Field\TextField::create('placeTwo'), 
            \Dat0r\Core\Runtime\Field\TextareaField::create('additionalInfos'), 
            \Dat0r\Core\Runtime\Field\IntegerField::create('pageNumber'), 
            \Dat0r\Core\Runtime\Field\TextareaField::create('ocrResult'), 
            \Dat0r\Core\Runtime\Field\KeyValueField::create('meta', array(                  
                'constraints' => array('value_type' => 'dynamic',),  
            )), 
            \Dat0r\Core\Runtime\Field\AggregateField::create('workflowTicket', array(                  
                'aggregate_module' => 'Honeybee\\Domain\\Book\\WorkflowTicketModule',  
            )), 
        ), array(             
            'prefix' => 'book',               
            'identifier_field' => 'identifier',               
            'baseModule' => '\\Honeybee\\Core\\Dat0r\\Module',               
            'baseDocument' => '\\Honeybee\\Core\\Dat0r\\Document',   
        ));
    }

    /**
     * Returns the IDocument implementor to use when creating new documents.
     *
     * @return string Fully qualified name of an IDocument implementation.
     */
    protected function getDocumentImplementor()
    {
        return 'Honeybee\Domain\Book\BookDocument';
    }
}
