<?php
/*              AUTOGENERATED CODE - DO NOT EDIT !
This base class was generated by the Dat0r library (https://github.com/berlinonline/Dat0r)
on 2013-08-27 16:43:20 and is closed to modifications by any meaning.
If you are looking for a place to alter the behaviour of 'Book' documents,
then the 'BookDocument' (skeleton) class probally might be a good place to look. */

namespace Honeybee\Domain\Book\Base;

use Honeybee\Core\Dat0r;

/**
 * Serves as the base class to the 'Book' document skeleton.
 */
abstract class BookDocument extends Dat0r\Document
{
    /**
     * Returns an 'Book' document's title.
     *
     * @return 
     */
    public function getTitle()
    {
        return $this->getValue('title');
    }

    /**
     * Sets an 'Book' document's title.
     *
     * @param  $title
     */
    public function setTitle($title)
    {
        $this->setValue('title', $title);
    }

    /**
     * Returns an 'Book' document's ssFlag.
     *
     * @return 
     */
    public function getSsFlag()
    {
        return $this->getValue('ssFlag');
    }

    /**
     * Sets an 'Book' document's ssFlag.
     *
     * @param  $ssFlag
     */
    public function setSsFlag($ssFlag)
    {
        $this->setValue('ssFlag', $ssFlag);
    }

    /**
     * Returns an 'Book' document's authorFirstname.
     *
     * @return 
     */
    public function getAuthorFirstname()
    {
        return $this->getValue('authorFirstname');
    }

    /**
     * Sets an 'Book' document's authorFirstname.
     *
     * @param  $authorFirstname
     */
    public function setAuthorFirstname($authorFirstname)
    {
        $this->setValue('authorFirstname', $authorFirstname);
    }

    /**
     * Returns an 'Book' document's authorLastname.
     *
     * @return 
     */
    public function getAuthorLastname()
    {
        return $this->getValue('authorLastname');
    }

    /**
     * Sets an 'Book' document's authorLastname.
     *
     * @param  $authorLastname
     */
    public function setAuthorLastname($authorLastname)
    {
        $this->setValue('authorLastname', $authorLastname);
    }

    /**
     * Returns an 'Book' document's additionalInfos.
     *
     * @return 
     */
    public function getAdditionalInfos()
    {
        return $this->getValue('additionalInfos');
    }

    /**
     * Sets an 'Book' document's additionalInfos.
     *
     * @param  $additionalInfos
     */
    public function setAdditionalInfos($additionalInfos)
    {
        $this->setValue('additionalInfos', $additionalInfos);
    }

    /**
     * Returns an 'Book' document's pageNumber.
     *
     * @return 
     */
    public function getPageNumber()
    {
        return $this->getValue('pageNumber');
    }

    /**
     * Sets an 'Book' document's pageNumber.
     *
     * @param  $pageNumber
     */
    public function setPageNumber($pageNumber)
    {
        $this->setValue('pageNumber', $pageNumber);
    }

    /**
     * Returns an 'Book' document's ocrResult.
     *
     * @return 
     */
    public function getOcrResult()
    {
        return $this->getValue('ocrResult');
    }

    /**
     * Sets an 'Book' document's ocrResult.
     *
     * @param  $ocrResult
     */
    public function setOcrResult($ocrResult)
    {
        $this->setValue('ocrResult', $ocrResult);
    }

    /**
     * Returns an 'Book' document's corrections.
     *
     * @return 
     */
    public function getCorrections()
    {
        return $this->getValue('corrections');
    }

    /**
     * Sets an 'Book' document's corrections.
     *
     * @param  $corrections
     */
    public function setCorrections($corrections)
    {
        $this->setValue('corrections', $corrections);
    }

    /**
     * Returns an 'Book' document's editions.
     *
     * @return 
     */
    public function getEditions()
    {
        return $this->getValue('editions');
    }

    /**
     * Sets an 'Book' document's editions.
     *
     * @param  $editions
     */
    public function setEditions($editions)
    {
        $this->setValue('editions', $editions);
    }

    /**
     * Returns an 'Book' document's meta.
     *
     * @return 
     */
    public function getMeta()
    {
        return $this->getValue('meta');
    }

    /**
     * Sets an 'Book' document's meta.
     *
     * @param  $meta
     */
    public function setMeta($meta)
    {
        $this->setValue('meta', $meta);
    }

    /**
     * Returns an 'Book' document's workflowTicket.
     *
     * @return 
     */
    public function getWorkflowTicket()
    {
        return $this->getValue('workflowTicket');
    }

    /**
     * Sets an 'Book' document's workflowTicket.
     *
     * @param  $workflowTicket
     */
    public function setWorkflowTicket($workflowTicket)
    {
        $this->setValue('workflowTicket', $workflowTicket);
    }
}
