<?php
/*              AUTOGENERATED CODE - DO NOT EDIT !
This base class was generated by the Dat0r library (https://github.com/berlinonline/Dat0r)
on 2013-09-17 04:17:31 and is closed to modifications by any meaning.
If you are looking for a place to alter the behaviour of the 'Book' module,
then the 'BookModule' (skeleton) class probally might be a good place to look. */

namespace Honeybee\Domain\Book\Base;

use Dat0r\Core\Field\AggregateField;
use Dat0r\Core\Field\BooleanField;
use Dat0r\Core\Field\IntegerField;
use Dat0r\Core\Field\KeyValueField;
use Dat0r\Core\Field\ReferenceField;
use Dat0r\Core\Field\TextField;
use Dat0r\Core\Field\TextareaField;
use Honeybee\Core\Dat0r;

/**
 * Serves as the base class to the 'Book'' module skeleton.
 */
abstract class BookModule extends Dat0r\Module
{
    /**
     * Creates a new BookModule instance.
     */
    protected function __construct()
    {
        parent::__construct(
            'Book',
            array(
                TextField::create(
                    'title',
                    array(
                        'mandatory' => true,
                    )
                ),
                BooleanField::create(
                    'ssFlag',
                    array()
                ),
                ReferenceField::create(
                    'author',
                    array(
                        'max' => 1,
                        'references' => array(
                            array(
                                'module' => '\\Honeybee\\Domain\\Author\\AuthorModule',
                                'identity_field' => 'identifier',
                                'display_field' => 'fullname',
                                'index_fields' => array(
                                    'firstname',
                                    'lastname',
                                    'fullname',
                                ),
                            ),
                        ),
                    )
                ),
                TextareaField::create(
                    'additionalInfos',
                    array()
                ),
                IntegerField::create(
                    'pageNumber',
                    array()
                ),
                TextareaField::create(
                    'ocrResult',
                    array()
                ),
                TextareaField::create(
                    'corrections',
                    array()
                ),
                AggregateField::create(
                    'editions',
                    array(
                        'modules' => array(
                            '\\Honeybee\\Domain\\Book\\EditionModule',
                        ),
                    )
                ),
                KeyValueField::create(
                    'meta',
                    array(
                        'constraints' => array(
                            'value_type' => 'dynamic',
                        ),
                    )
                ),
                AggregateField::create(
                    'workflowTicket',
                    array(
                        'modules' => array(
                            '\\Honeybee\\Domain\\Book\\WorkflowTicketModule',
                        ),
                    )
                ),
            ),
            array(
                'prefix' => 'book',
                'identifier_field' => 'identifier',
                'slugPattern' => '{title}-{shortId}',
            )
        );
    }

    /**
     * Returns the IDocument implementor to use when creating new documents.
     *
     * @return string Fully qualified name of an IDocument implementation.
     */
    protected function getDocumentImplementor()
    {
        return '\\Honeybee\\Domain\\Book\\BookDocument';
    }
}
