<?php
/*              AUTOGENERATED CODE - DO NOT EDIT !
This base class was generated by the Dat0r library (https://github.com/berlinonline/Dat0r)
on 2013-08-27 16:43:20 and is closed to modifications by any meaning.
If you are looking for a place to alter the behaviour of 'Edition' documents,
then the 'EditionDocument' (skeleton) class probally might be a good place to look. */

namespace Honeybee\Domain\Book\Base;

use Dat0r\Core\Document;

/**
 * Serves as the base class to the 'Edition' document skeleton.
 */
abstract class EditionDocument extends Document\Document
{
    /**
     * Returns an 'Edition' document's publisher.
     *
     * @return 
     */
    public function getPublisher()
    {
        return $this->getValue('publisher');
    }

    /**
     * Sets an 'Edition' document's publisher.
     *
     * @param  $publisher
     */
    public function setPublisher($publisher)
    {
        $this->setValue('publisher', $publisher);
    }

    /**
     * Returns an 'Edition' document's location.
     *
     * @return 
     */
    public function getLocation()
    {
        return $this->getValue('location');
    }

    /**
     * Sets an 'Edition' document's location.
     *
     * @param  $location
     */
    public function setLocation($location)
    {
        $this->setValue('location', $location);
    }

    /**
     * Returns an 'Edition' document's year.
     *
     * @return 
     */
    public function getYear()
    {
        return $this->getValue('year');
    }

    /**
     * Sets an 'Edition' document's year.
     *
     * @param  $year
     */
    public function setYear($year)
    {
        $this->setValue('year', $year);
    }
}
