<?php
/*              AUTOGENERATED CODE - DO NOT EDIT !
This base class was generated by the Dat0r library (https://github.com/berlinonline/Dat0r)
on 2013-09-17 04:17:31 and is closed to modifications by any meaning.
If you are looking for a place to alter the behaviour of the 'Edition' module,
then the 'EditionModule' (skeleton) class probally might be a good place to look. */

namespace Honeybee\Domain\Book\Base;

use Dat0r\Core\Field\ReferenceField;
use Dat0r\Core\Field\TextField;
use Dat0r\Core\Module;

/**
 * Serves as the base class to the 'Edition'' module skeleton.
 */
abstract class EditionModule extends Module\AggregateModule
{
    /**
     * Creates a new EditionModule instance.
     */
    protected function __construct()
    {
        parent::__construct(
            'Edition',
            array(
                TextField::create(
                    'location',
                    array()
                ),
                TextField::create(
                    'year',
                    array()
                ),
                ReferenceField::create(
                    'publisher',
                    array(
                        'max' => 1,
                        'references' => array(
                            array(
                                'module' => '\\Honeybee\\Domain\\Publisher\\PublisherModule',
                                'identity_field' => 'identifier',
                                'display_field' => 'name',
                            ),
                        ),
                    )
                ),
            ),
            array()
        );
    }

    /**
     * Returns the IDocument implementor to use when creating new documents.
     *
     * @return string Fully qualified name of an IDocument implementation.
     */
    protected function getDocumentImplementor()
    {
        return '\\Honeybee\\Domain\\Book\\EditionDocument';
    }
}
