<?php
/*                  AUTOGENERATED SKELETON CLASS
This skeleton class was generated by the Dat0r library (https://github.com/berlinonline/Dat0r) 
on 2013-04-16 16:54:10 and allows to alter the behaviour of the 'Book' module.
This file is only generated if doesn't exist so eventual modifications are safe. */

namespace Honeybee\Domain\Book;

/**
 * The BookModule class reflects the declared structure of the 'Book' entity.
 * It holds the meta data necessary to manage/initiate 'BookDocument' lifecycles.
 */
class BookModule extends \Honeybee\Domain\Book\Base\BookModule
{
    
}
