<?php
/*                  AUTOGENERATED SKELETON CLASS
This skeleton class was generated by the Dat0r library (https://github.com/berlinonline/Dat0r) 
on 2013-04-16 16:54:10 and allows to alter the behaviour of 'Book' documents.
This file is only generated if doesn't exist so eventual modifications are safe. */

namespace Honeybee\Domain\Book;

/**
 * Holds the structure definition for Book documents.
 */
class BookDocument extends \Honeybee\Domain\Book\Base\BookDocument
{
    
}
