<?php
/*                  AUTOGENERATED SKELETON CLASS
This skeleton class was generated by the Dat0r library (https://github.com/berlinonline/Dat0r)
on 2013-08-27 16:43:20 and allows to alter the behaviour of the 'PluginResult' module.
This file is only generated if doesn't exist so eventual modifications are safe. */

namespace Honeybee\Domain\Book;

use Honeybee\Domain\Book\Base;

/**
 * The PluginResultModule class reflects the declared structure of the 'PluginResult' entity.
 * It holds the meta data necessary to manage/initiate 'PluginResultDocument' lifecycles.
 */
class PluginResultModule extends Base\PluginResultModule
{

}
