# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant::Config.run do |config|
  config.vm.define :devbox do |devbox|
    devbox.vm.box = "ubuntu-12.10-x64"
    devbox.vm.box_url = "http://24-hetzner.berlinonline.de/ubuntu-12.10-x64.box"

    config.vm.customize ["modifyvm", :id, "--rtcuseutc", "on"] # use UTC clock instead of host clock, see https://github.com/mitchellh/vagrant/issues/912
    config.vm.customize ["modifyvm", :id, "--name", "banned_books-devbox"] # name for VirtualBox GUI

    config.vm.host_name = "cms.banned-books.dev"
    config.hosts.aliases = %w(banned-books.dev)

    devbox.vm.network :hostonly, "33.33.33.10"
    devbox.ssh.forward_agent = true

    config.vm.provision :shell, :inline =>'[ "$(find /home/vagrant/ -maxdepth 1 -name apt_updated -mtime -48)" == "" ] && apt-get update --fix-missing && touch /home/vagrant/apt_updated; echo ""'

    devbox.vm.provision :puppet do |puppet|
      puppet.manifests_path = "./"
      puppet.manifest_file = "manifest.pp"
      puppet.module_path = [ "../../modules", "../../../puppets/modules" ]
      #puppet.options = "--verbose --debug"
    end
  end

end
