<?php
/*              AUTOGENERATED CODE - DO NOT EDIT !
This base class was generated by the Dat0r library (https://github.com/berlinonline/Dat0r)
on 2013-09-17 00:49:48 and is closed to modifications by any meaning.
If you are looking for a place to alter the behaviour of the 'Publisher' module,
then the 'PublisherModule' (skeleton) class probally might be a good place to look. */

namespace Honeybee\Domain\Publisher\Base;

use Dat0r\Core\Field\AggregateField;
use Dat0r\Core\Field\KeyValueField;
use Dat0r\Core\Field\TextField;
use Honeybee\Core\Dat0r;

/**
 * Serves as the base class to the 'Publisher'' module skeleton.
 */
abstract class PublisherModule extends Dat0r\Module
{
    /**
     * Creates a new PublisherModule instance.
     */
    protected function __construct()
    {
        parent::__construct(
            'Publisher',
            array(
                TextField::create(
                    'name',
                    array(
                        'mandatory' => true,
                    )
                ),
                KeyValueField::create(
                    'meta',
                    array(
                        'constraints' => array(
                            'value_type' => 'dynamic',
                        ),
                    )
                ),
                AggregateField::create(
                    'workflowTicket',
                    array(
                        'modules' => array(
                            '\\Honeybee\\Domain\\Publisher\\WorkflowTicketModule',
                        ),
                    )
                ),
            ),
            array(
                'prefix' => 'publisher',
                'identifier_field' => 'identifier',
                'slugPattern' => 'publisher-{shortId}',
            )
        );
    }

    /**
     * Returns the IDocument implementor to use when creating new documents.
     *
     * @return string Fully qualified name of an IDocument implementation.
     */
    protected function getDocumentImplementor()
    {
        return '\\Honeybee\\Domain\\Publisher\\PublisherDocument';
    }
}
